version: "3.9"
services:
  web:
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: lottoapi_app
    ports:
      - "8001:8000"  # Expose the app on port 8000
    volumes:
      - .:/app  # Mount current directory into the container (useful for development)
    environment:
      - APP_ENV=production
      - BASE_URL=http://localhost:8001  # Corrected BASE_URL for exposed port
      - DATABASE_URL=postgresql://postgres:310302@localhost:5432/Teaching  # Connect to 'postgres' container
    command: uvicorn index:app --host 0.0.0.0 --port 8000 --reload

#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: "310302"
#       POSTGRES_DB: Teaching
#     ports:
#       - "5433:5432"  # Expose PostgreSQL on port 5433 on the host
#     networks:
#       - lottoapi_net

# networks:
#   lottoapi_net:
#     driver: bridge

  # Uncomment this section if you need a database like PostgreSQL
  # db:
  #   image: postgres:15
  #   container_name: fastapi_db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: fastapi_db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# Uncomment if using a database
# volumes:
#   db_data:
